### ISSUE TITLE
Allow rust monster configs to pick up on oredictionary definitions

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/dungeon-mobs#15]
Since many things have oredictionary definitions, this could prove useful when dealing with say, multiple mods that add various forms of copper.

**Comment by BlackJar72** [comment]
I may look into it some time, but it could get a bit complicated depending on how its done.  Iterating registered items in post-init (similar to how Doomlike Dungeons exports block and item lists) would probably be the basis.  Then it would need to check each item against a list of ore dictionary entries (not sure how to do this off the top of my head).  Could be a bit slow (O{m,n) = m*n), but might not be to bad during start-up.

I'll be slowing down on these things -- its become self-destructive the amount of time that goes into these modding binges and letting too many other things go.

**Comment by BlackJar72** [comment]
Any block or item should work.  I'd have to look at it again, but one short coming I hadn't thought of before is that I don't think it understands meta data at this point.  That may very well be something that needs fixing.  But beyond that it can be anything in the game that can exist as an Item.

**Comment by Sunconure11** [comment]
Can we add a config setting to allow it to spawn near a list of modded ores, in addition to the ones from vanilla? Since one behavior of it is to spawn by such.

**Comment by Sunconure11** [comment]
I was tired, and was trying to cover as many modded ingots as possible

**Comment by Sunconure11** [comment]
Okay, it looks like configs are not working in general for the rust monster

**Comment by BlackJar72** [comment]
OK, I'll have to look into sometime over the weekend I guess.

**Comment by BlackJar72** [comment]
Well, I fixed the bug where they don't use the food list at all -- I had them eating bricks and leaves for a test and it worked fine.

I'll look into the other fixes and enhancements later.

**Comment by BlackJar72** [comment]
No, it definitely won't work with damage / meta values -- its a set of Item, not ItemStack.  Items don't have that data, stacks do.  It would really complicate things to have it use ItemStacks, though I can see how this could be a problem with mods that use "god items."

**Comment by Sunconure11** [comment]
There are mods that assign meta values as to conserve on IDs. An example would be thaumcraft, all of it's ingots are technically one item, just with differing meta.

**Comment by BlackJar72** [comment]
Yes, Minefantasy does that extensively -- basically one item for pretty much anything without a durability or special feature, hundreds of versions of ItemComponent representing everything from ingots to wood to glew to money.  That's what I call a god item -- one all mighty item to be everything.

However, to do this would require rewriting a lot of code, and a whole new class, etc., to make it work.

Unfortunately my glasses have broken, and what I have for back-ups makes it very hard to look at screens, which I'll be doing as little of as I can for the next little bit.  So, I won't be writing any code for any project for probably a least a week.  Sorry, things will just have to stand as they are for now.

**Comment by Sunconure11** [comment]
Also, just in case, but since you are using a similar set up for entities to spawn from the shrieker, you might  want to test that too.

**Comment by BlackJar72** [comment]
I already tested the shrieker -- it works, that always did.

**Comment by BlackJar72** [comment]
My glasses can't be fixed, and my eyes are getting to where I can't read screens at all.  It will probaly be several weeks before I can do any more -- even respond to issues / posts.

**Comment by Sunconure11** [comment]
Config system may have broken, resulting in crashes. Investigating.

https://pastebin.com/TbXbUKi7

**Comment by BlackJar72** [comment]
I used the wrong method to translate the string data into a number for meta data.  Its now fixed in the repo.  You may test and uploaded when ready.

(Frankly, I'm getting tire of this and ready for a total break.)

**Comment by BlackJar72** [comment]
Never mind I'll upload the fix.  Then, I don't know.  I'll leave it to you to close the issue when you're satisfied.

**Comment by Sunconure11** [comment]
I'm at a loss for words, it's still happening.

Here is my config:

https://pastebin.com/d5ikjNAk

**Comment by BlackJar72** [comment]
The exact same crash?!  That doesn't make sense.  If anything is mistyped or not found -- any errors in the list -- and it will definitely crash.  But I can't see any way the old crash could still happen with the latest version (which was tested here and works).

Anyway, not time to fool with it now.
